 version: '3.1'

 services:
   postgres:
     image: 'postgres:13.3'
     environment:
       - POSTGRES_USER=user
       - POSTGRES_PASSWORD=password
       - POSTGRES_DB=user_mng_db
     ports:
       - "5432:5432"
     volumes:
       - ./.database/postgres/data:/var/lib/postgresql/data
   app:
     image: 'user_manager-app'
     build:
       context: .
     environment:
       - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/user_mng_db
     ports:
       - "8080:8080"
     depends_on:
       - postgres