DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name        VARCHAR                           NOT NULL,
    password         VARCHAR                           NOT NULL,
    first_name       VARCHAR                           NOT NULL,
    last_name        VARCHAR                           NOT NULL,
    role             VARCHAR,
    status           VARCHAR,
    created_at       TIMESTAMP           DEFAULT now() NOT NULL
);
CREATE UNIQUE INDEX users_unique_username_idx ON users (user_name);



INSERT INTO users (user_name, password, first_name, last_name, role, status)
VALUES ('user', '$2y$12$RXhh6rTWS3ELOZWgEVvZCevoP8RDPMC6Ge0WKAWOlEjcSlG22Geea', 'userFirstName', 'userLastName', 'USER', 'ACTIVE'),
       ('admin', '$2y$12$HxgHzGPlo69EDzLk8GB4VO7ponxtuBLMz80rlA6Iz2hkZBBxMWkf2', 'adminFirstName', 'adminLastName', 'ADMIN', 'ACTIVE');

