DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name        VARCHAR                           NOT NULL,
    password         VARCHAR                           NOT NULL,
    first_name       VARCHAR                           NOT NULL,
    last_name        VARCHAR                           NOT NULL,
    role             VARCHAR,
    status           VARCHAR,
    created_at       TIMESTAMP           DEFAULT now() NOT NULL
);
CREATE UNIQUE INDEX users_unique_username_idx ON users (user_name);



INSERT INTO users (user_name, password, first_name, last_name, role, status)
VALUES ('User1', '{noop}password1', 'userFirstName', 'userLastName', 'USER', 'ACTIVE'),
       ('Admin', '{noop}admin', 'adminFirstName', 'adminLastName', 'ADMIN', 'ACTIVE');

